dist: trusty
git:
  depth: false
addons:
  sonarcloud:
    organization: "odococo"
    token:
        secure: "gehu26JC6HFpJ8GzokeinWul+TtZ/xRPfcB7H516K6bp1CVW9/81DRduNSXd+1gF5HSVZhQYj5i6uifrwYfqa+lY1YJWI62nc5PtU9AIDGDrnmtWMd4LD8alAm9+tAFawiuWbgwNUFjLKGqHBXjaqkpjwrL2QVkBhCs9VlG/7Nhn9hjZmWf379W1ajrdk2hntp8VqTjgT9JL7az6OxAhOLCRGGLO3xsGRXO6ZN8x94AvYBKe8Zn84ctV21nAxy4Hpg3Xi317eoux/3qM3Ej4Ir28KHJT3LIKqX14KZqIcNxZlmX2Er+BpfTTNu2iVm3ZFFhJUHYoVtMvrhj2yqsw0EptGCFBEB59yPImAEPHDF1Dzg6VUrq4638qMMZNQEp/LpZHsmV0dQ9699XK0DeKEIoMMaGUx0s6oQc1vrROHSpMvxAk12OtO5VLjgjYAzxGpHK8cvnPt4HgO9laj1057JOdghizN6RClka/SNMy7jrmEDmegovPkxWsR4HsEBE42B3WoMUHQbMSxBrhsuUHxFeFx8XA2QFHvb+dw502vL0LcNWtQDHCZukLw7f9TPkQ/UeDPexbpRJYw6HrORlKpwhPoetpLOL0ioDfjI2JWWP9rfwLk9uK6ihBfx6VbbeU0H3ky1LPwc5KNBbcNwZdH3GQBSsyCSXKA+z7i7Pg97U="

language: python
python:
- '3.6'
before_install:
  - pip install --upgrade pytest
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=bioinformatica --cov-report xml:coverage.xml 
- coverage combine --append || true
- coverage report
- coverage xml
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
